datasets:
  type: div2k

  dataset: 
    status: test
    args: 

model: 
  type: metasr
  args:
    encoder: 
      type: rdn
      args: 
        no_upsample: True
    mlp_decoder: 
      out_dim: 3
